Revert "- updated to 4.12.3"
This reverts commit 67c1e92a94fc6c5f580eb525c3287a0a9239aa5a.

4.12.3 is plain broken, and breaks too many dependant programs in return
- import PyQt4 complains about sip and fails on every first import
- from PyQt4.QtCore import PYQT_VERSION
ImportError: cannot import name PYQT_VERSION